make: Improve `mw` and `makew`
Duplicate code was factored out and messages were added along with
better error handling. It now asks whether or not you want to continue
in case `make` fails.

diff --git a/make/.config/shell/make/aliases b/make/.config/shell/make/aliases
--- a/make/.config/shell/make/aliases
+++ b/make/.config/shell/make/aliases
@@ -1,22 +1,43 @@
 # shellcheck shell=sh
 
-# Make using my cool rules.
-alias m='make -f ${XDG_CONFIG_HOME:-$HOME/.config}/make/makefile'
-
-mw () {
-    echo "Watching..."
-    while true; do
-        # shellcheck disable=SC2048,SC2086
-        m -q $* || m $*
-        sleep 1
-    done
+# make, but using my cool custom rules.
+m() {
+    make -f "${XDG_CONFIG_HOME:-$HOME/.config}"/make/makefile "$@"
 }
 
-makew () {
-    echo "Watching..."
+# make, but continuously watching for outdated targets.
+alias mw='_makew_common m'
+alias makew='_makew_common make'
+
+_makew_common () {
+    cmd="$1"
+    always=false
+    shift
+
+    echo "${cmd}w: Watching..."
+
     while true; do
-        # shellcheck disable=SC2048,SC2086
-        make -q $* || make $*
-        sleep 1
+        $cmd -q "$@"
+        exit_status=$?
+
+        if [ "$exit_status" -eq 1 ]; then
+            echo "${cmd}w: Target was not up-to-date."
+            $cmd "$@"
+            exit_status=$?
+        fi
+
+        if [ "$exit_status" -ne 0 ] && [ "$always" != "true" ]; then
+            printf "%sw: An error occurred. Continue? [Y/n/a] " "$cmd"
+            read -r answer
+            case "$answer" in
+                [Nn]*) break ;;
+                [Aa]*) always=true ;;
+                *)     ;;
+            esac
+        else
+            sleep 1
+        fi
     done
+
+    return "$exit_status"
 }
