lua: Avoid running `luarocks` if possible

diff --git a/lua/.config/shell/lua/profile b/lua/.config/shell/lua/profile
--- a/lua/.config/shell/lua/profile
+++ b/lua/.config/shell/lua/profile
@@ -1,6 +1,15 @@
 # shellcheck shell=sh
 
+# NOTE: LuaRocks takes a while to load, so we don't want to do it more
+# than once if not needed.
+# FIXME: Make LuaRocks faster. I believe this is because we're using the x86_64
+# build on Apple Sillicon.
+case ";$LUA_PATH;" in
+    *";$HOME/.luarocks/share/lua/"*"/?/init.lua;") return 0 ;;
+    *) ;;
+esac
+
 if ! shell_eval_if_succeeds luarocks path --no-bin; then
-    echo "luarocks not installed" >&2
+    echo "luarocks: failed to eval luarocks" >&2
     return 1
 fi
